export const serverInfo = {
  name: "NO LIMITS ROLEPLAY",
  status: "Online" as const,
  players: 127,
  maxPlayers: 200,
  queue: 5,
  capacity: 63.5,
  ipAddress: "45.142.220.135:30120",
  uptime: "7d 14h 32m",
  version: "FiveM v2.1.5",
}

export const userData = {
  name: "Astra",
  playerId: "#12345",
  level: 45,
  playTime: "247h 32m",
  playTimeChange: "+5h 12m this week",
  bankBalance: 2847950,
  balanceChange: "+$125,000 this week",
  currentJob: "Police Officer",
  rank: "Sergeant",
}

export const recentOnlinePlayers = [
  { name: "Sarah_Connor", avatar: "/female-avatar-1.png", time: "2 min ago" },
  { name: "Mike_Johnson", avatar: "/male-avatar-1.png", time: "5 min ago" },
  { name: "Emma_Davis", avatar: "/female-avatar-2.png", time: "12 min ago" },
  { name: "Alex_Smith", avatar: "/male-avatar-2.png", time: "18 min ago" },
  { name: "Lisa_Wilson", avatar: "/female-avatar-3.png", time: "25 min ago" },
]

export const mostActivePlayers = [
  { rank: 1, name: "Tony_Montana", avatar: "/gangster-avatar.png", hours: "892h" },
  { rank: 2, name: "Frank_Castle", avatar: "/punisher-avatar.jpg", hours: "784h" },
  { rank: 3, name: "Jessica_Parker", avatar: "/blonde-female-avatar.jpg", hours: "672h" },
  { rank: 4, name: "Mike_Johnson", avatar: "/casual-male-avatar.png", hours: "589h" },
  { rank: 5, name: "Sarah_Connor", avatar: "/tough-female-avatar.jpg", hours: "534h" },
]

export const richestPlayers = [
  { rank: 1, name: "Frank_Castle", avatar: "/rich-man-avatar.jpg", money: "$15.2M" },
  { rank: 2, name: "Tony_Montana", avatar: "/businessman-avatar.png", money: "$12.8M" },
  { rank: 3, name: "Alex_Smith", avatar: "/wealthy-avatar.jpg", money: "$9.4M" },
  { rank: 4, name: "Jessica_Parker", avatar: "/rich-woman-avatar.jpg", money: "$7.9M" },
  { rank: 5, name: "John_Doe", avatar: "/anonymous-avatar.png", money: "$2.8M" },
]

export const leaderboardPlayers = [
  {
    rank: 1,
    name: "HeadshotKing",
    avatar: "/pro-gamer-avatar.jpg",
    status: "Online",
    kills: 12847,
    deaths: 2341,
    kdRatio: 5.49,
    headshots: 4521,
    winRate: 78,
  },
  {
    rank: 2,
    name: "SilverSniper",
    avatar: "/sniper-avatar.png",
    status: "Online",
    kills: 8432,
    deaths: 2156,
    kdRatio: 3.91,
    headshots: 3012,
    winRate: 72,
  },
  {
    rank: 3,
    name: "ProGamer47",
    avatar: "/esports-avatar.jpg",
    status: "Offline",
    kills: 7921,
    deaths: 2089,
    kdRatio: 3.79,
    headshots: 2845,
    winRate: 70,
  },
  {
    rank: 4,
    name: "TacticalNinja",
    avatar: "/ninja-avatar.png",
    status: "Online",
    kills: 7654,
    deaths: 2234,
    kdRatio: 3.43,
    headshots: 2891,
    winRate: 67,
  },
  {
    rank: 5,
    name: "QueenSniper",
    avatar: "/regal-avatar.png",
    status: "Offline",
    kills: 7123,
    deaths: 2456,
    kdRatio: 2.9,
    headshots: 3124,
    winRate: 64,
  },
  {
    rank: 6,
    name: "ShadowHunter",
    avatar: "/shadow-avatar.jpg",
    status: "Online",
    kills: 6892,
    deaths: 2187,
    kdRatio: 3.15,
    headshots: 2567,
    winRate: 71,
  },
  {
    rank: 7,
    name: "BattleQueen",
    avatar: "/warrior-queen-avatar.jpg",
    status: "Online",
    kills: 6543,
    deaths: 2341,
    kdRatio: 2.79,
    headshots: 2234,
    winRate: 59,
  },
  {
    rank: 8,
    name: "EliteAssassin",
    avatar: "/assassin-avatar.jpg",
    status: "Offline",
    kills: 6234,
    deaths: 2098,
    kdRatio: 2.97,
    headshots: 2456,
    winRate: 62,
  },
  {
    rank: 9,
    name: "PhantomKiller",
    avatar: "/phantom-avatar.jpg",
    status: "Online",
    kills: 5987,
    deaths: 2234,
    kdRatio: 2.68,
    headshots: 2123,
    winRate: 58,
  },
  {
    rank: 10,
    name: "WarMachine",
    avatar: "/machine-avatar.jpg",
    status: "Offline",
    kills: 5765,
    deaths: 2456,
    kdRatio: 2.35,
    headshots: 1987,
    winRate: 55,
  },
]

export const recentTickets = [
  {
    id: "#TK-2024-001",
    subject: "Player breaking FRP rules",
    category: "FRP",
    priority: "High",
    status: "In Progress",
    created: "2 hours ago",
  },
  {
    id: "#TK-2024-002",
    subject: "Vehicle spawning bug",
    category: "Bug",
    priority: "Medium",
    status: "Resolved",
    created: "1 day ago",
  },
  {
    id: "#TK-2024-003",
    subject: "Account access issue",
    category: "Other",
    priority: "Low",
    status: "Resolved",
    created: "3 days ago",
  },
]

export const ticketCategories = [
  {
    id: "frp",
    name: "FRP Issues",
    description: "Report players who are not following proper roleplay guidelines or breaking character.",
    icon: "alert",
    responseTime: "2-4 hours",
  },
  {
    id: "bug",
    name: "Bug Reports",
    description: "Report technical issues, glitches, or problems with server functionality.",
    icon: "bug",
    responseTime: "1-2 hours",
  },
  {
    id: "other",
    name: "Other",
    description: "General questions, account issues, or other concerns not covered above.",
    icon: "help",
    responseTime: "4-8 hours",
  },
]
